### ISSUE TITLE
Dev 브랜치 이미지 경로 오류

### ISSUE THREAD

**Issue by neruu00** [Codeit-Sprint-Part-3-Team-8/Taskify#38]
## ✨ 요약

이미지의 경로는 변경되었지만 스크립트에는 변경사항이 반영되지 않아 빌드 에러가 발생합니다.

![image](https://github.com/user-attachments/assets/d183b3a0-6559-42b9-8d7f-1dad0fdc3a73)

![image](https://github.com/user-attachments/assets/c98f2b31-1eb6-4a29-8c48-e99adddd481a)

## #️⃣ 생성할 브랜치

-  feat/18--landingpage-init/38--bug

## 🔨 작업 내용

- [ ] `app/page.tsx`에서 이미지 경로 수정하기

## 📝 자세한 설명

> 작업할 내용에 대해 자세한 내용을 작성해 주세요

**Comment by yunrap** [comment]
네!~ 오류 확인했습니다.
확인안하고 올렸었네요 
수정하여 pr 날리겠습니다.
